cc_binary (
    name = "main",
    srcs = [
        "main.cc",
    ],
    deps = [
        ":server",
    ],
)

cc_library (
    name = "server",
    srcs = [
        "server.cc",
    ],
    hdrs = [
        "server.h",
    ],
)